### PR TITLE
Do not mark alcotest skipped tests as failure

### LINKED ISSUE #9: Skipped alcotest tests showing up as failures in Junit
Example build for our repo: https://github.com/hazelgrove/hazel/actions/runs/12432886131/job/34713395956

Alcotest test output:
```
 [SKIP]        MenhirParser          0   Example failure.
 ```
 
 Junit.xml
 ```
 <testsuites>
    <testsuite package="HazelTests" id="0" name="HazelTests" timestamp="2024-12-20T14:40:16"
        hostname="localhost" tests="1" failures="0" errors="1" time="0">
        <properties></properties>
        <testcase name="Example failure" classname="HazelTests.MenhirParser" time="0">
            <error message="test crashed" type="exception raised">Alcotest_engine__Core.Skip</error>
        </testcase>
    </testsuite>
</testsuites>
```

I can work on a PR if that would be welcomed.

### PR DESCRIPTION
**Pull request by Khady**
fix #9

### CODE REVIEW

**Comment by Khady** [comment]
@7h3kk1d if you think this output is good for you then I’ll merge and make a release.

**Comment by 7h3kk1d** [comment]
> @7h3kk1d if you think this output is good for you then I’ll merge and make a release.

@Khady We're also using dorny/test-reporter@v1 and it seems like this is showing up as skipped tests :+1:. Looking at the test suite output though I would have expected  skipped to be present as a property to track the total number of skipped tests. As long as it works with the test reporter though it doesn't really matter to us, but it might affect other tools?

```xml
<testsuite package="junit_alcotest" id="0" name="Skip test suite" timestamp="2013-05-24T10:23:58" hostname="localhost" tests="2" failures="0" errors="0" time="0">
```

**Comment by Khady** [comment]
This was written a long time ago, so I don't really remember the details. From what I can see in the spec files and the comments, not all junit tools supported skipped tests. It's also not present in ounit's output

https://github.com/gildor478/ounit/blob/3c0464871690562b93bd2501811d5a4b9821a5aa/src/lib/ounit2/advanced/oUnitLoggerJUnit.ml#L61-L70

https://github.com/testmoapp/junitxml has this skipped field. 85a51363bc3e98552ca7fbeeecec964f7aed6891 doesn't seem to break things in github at least. Unfortunately the circleci integration was broken and I've not gitlab or jenkins at hand to validate the output. But I suppose we can consider it good to go.

**Comment by Khady** [comment]
@7h3kk1d version 2.1.0 has been released

**Comment by 7h3kk1d** [comment]
Awesome, https://github.com/hazelgrove/hazel/actions/runs/12484613033/job/34842444146 is now showing up with skipped tests.

@Khady Not load bearing for our use case. But the direct alcotest output is now showing those tests as `[OK]` as opposed to `[SKIP]`. I think this is because you're not reraising the skip exception in `wrap_test`. Sorry I didn't catch this before the merge/deploy, I was just looking at the junit output.

**Comment by Khady** [comment]
Good catch! Thanks

**Pull request merged**
